import digitalBook from "@/assets/images/compressed/digital-book.jpg";
import lullaby from "@/assets/images/compressed/lullaby.jpg";
import poster from "@/assets/images/compressed/poster.jpg";
import poster1 from "@/assets/images/compressed/poster1-min.jpg";
import postcard from "@/assets/images/compressed/postcard.jpg";
import postcard1 from "@/assets/images/compressed/postcard-open1-min.jpg";
import postcard2 from "@/assets/images/compressed/postcard-open2-min.jpg";
import postcard3 from "@/assets/images/compressed/postcard-open3-min.jpg";
import book1 from "@/assets/images/compressed/book-open1-min.jpg";
import book2 from "@/assets/images/compressed/book-open2-min.jpg";

import certificate from "@/assets/images/certificate.png";

export const includedProducts = [
  {
    title: "Digital Illustrated Book",
    element: "digital-book",
    description:
      "Crafted to inspire hope and bring joy to bedtime. You can read it together or explore the beautiful world our illustrator created, with exciting finds to discover with every reading.",
    imagePath: [digitalBook],
    to: "/donation/digital-book",
    weight: 0,
  },
  {
    title: "Lullaby",
    element: "lullaby",
    description:
      "A soothing lullaby recording, created to bring comfort to young hearts—both those who are safe at home and those whose homes are touched by conflict. It pairs perfectly with our illustrated book but is equally enchanting on its own.",
    imagePath: [lullaby],
    to: "/donation/lullaby",
    weight: 0,
  },
  {
    title: "Digital Donation Certificate",
    element: "certificate",
    description:
      "A personalised digital certificate acknowledging your support for children's psychological rehabilitation.",
    imagePath: [certificate],
    to: "/donation/certificate",
    weight: 0,
  },
];

export const extraProducts = [
  {
    title: "Printed Book",
    element: "book",
    description:
      "A printed copy of our digital illustrated book, perfect for bringing stories of hope, joy and adventure to your home.",
    imagePath: [book1, book2],
    to: "/donation/book",
    weight: 2,
    size: "21.0 x 29.7 cm",
  },
  {
    title: "Poster",
    element: "poster",
    description:
      "A poster featuring an illustration from our project, filled with adventure and creativity.",
    imagePath: [poster, poster1],
    to: "/donation/poster",
    weight: 2,
    size: "42 x 29.7 cm",
  },
  {
    title: "Postcards",
    element: "postcards",
    description:
      "A set of seven postcards reflecting the spirit of our project, perfect for sending messages of kindness.",
    imagePath: [postcard, postcard1, postcard2, postcard3],
    to: "/donation/postcards",
    weight: 0.375,
    size: "14.8 x 10.5 cm",
  },
];

export const creatorsData = [
  {
    name: "Afrika Fuentes",
    location: "Manchester, UK",
    description:
      'is a Soul and R&B singer, songwriter and keyboard player. After winning the ‘BBC New Talent Award’ for new songwriters in 2008, she launched her songwriting career under the mentorship of Cathy Dennis; hit songwriter for Britney Spears and Kylie Minogue. In 2012 Afrika signed a publishing deal with Sony ATV and released her acclaimed single "Rainbow", which was well received in her native Spain. Currently she writes for pop artists and labels worldwide. Her song “Ay Dios Mío” was recorded by Spanish girl band Sweet California, peaking at number one in the Spanish album charts in 2017 with their album “3”.',
    link: "https://www.linkedin.com/in/afrika-fuentes-84133a3b/?originalSubdomain=uk",
  },
  {
    name: "Ksenia Urban",
    location: "Poland",
    description:
      "is a n illustrator living in Poland. She's been drawing and creating art professionally for about 10 years. Through her illustrations, she aims to inspire both children and adults to see the world in a new and magical way.",
    link: "https://www.behance.net/kseniaurban",
  },
  {
    name: "Inna Solodniuk (Ishchenko)",
    location: "Kiev, Ukraine",
    description:
      "is a bandurist, indie-soul singer, and songwriter, also known as Solo Inna. She is a super-finalist on 'Voice of the Country 6' and also participated in 'X-Factor.' In 2016, she performed the song 'Plyne Kacha' on 'Voice of the Country,' which garnered 9 million views. Currently, Inna is dedicated to supporting the moral and psychological well-being of the military and promoting Ukrainian culture. The Voice Ukraine ('Holos Krainy') is part of the international syndication The Voice.",
    link: "https://www.youtube.com/@inna.solodniuk",
  },
  {
    name: "Teo Nalani",
    location: "Brooklyn, NY, US",
    description:
      "is a 2d animator and Illustrator based in Brooklyn, NY, US. His art is influenced strongly by personal memory, forces of nature and storms, boxing, and fashion. He believes in instincts and imagination, and is always looking for things that are hard to find.",
    link: "https://www.teonalani.com/",
  },
  {
    name: "Danbi Kim",
    location: "Berlin, Germany",
    description:
      "is a UX/UI designer and trilingual calligrapher with a rich multicultural background and a genuine curiosity about the world. Her diverse experiences and unique perspectives infuse her work with vibrant and varied designs. She is dedicated to creating meaningful experiences for diverse audiences through her design approach.",
    link: "https://danbikim.studio.site/",
  },
  {
    name: "Ivan Vernihora",
    location: "Berlin, Germany",
    description:
      "He's a fullstack developer with a strong passion for building scalable and efficient applications. As a student at 42 Berlin, he's constantly honing his problem-solving skills and diving deep into software development. Beyond coding, he loves the thrill of snowboarding, enjoying the mountains and the adrenaline rush. Whether it's tackling complex algorithms or carving through fresh powder, he's always up for a challenge!",
    link: "https://www.linkedin.com/in/ivan-vernihora",
  },
  {
    name: "Propeller Studios",
    location: "Kiev, Ukraine",
    description:
      "is a sound production company based in Kyiv, Ukraine. Their team comprises highly qualified sound designers, audio engineers, music composers, and producers. Propeller Studios collaborates with top musicians, actors, and voice talents. With years of professional experience, they consistently create high-quality audio products alongside their clients.",
    link: "https://www.propeller.com.ua/ ",
  },
  {
    name: "Fyodor Stepanov",
    location: "Berlin, Germany",
    description:
      "is a sound artist and composer. His creative output is driven by notions of transience, non-linearity, and ambiguity intrinsic to sound. The approach he has developed over the past decade combines generative algorithms with bits of radio broadcasts, field recordings, and electromagnetic listening to produce eerie acousmatic soundscapes.",
    link: "https://fyodor-st.bandcamp.com/music",
  },
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Other",
];

export const availableCountries = [
  "Africa",
  "Albania",
  "Andorra",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Azores",
  "Balaeric Islands",
  "Belarus",
  "Belau",
  "Belgium",
  "Bosnia & Herzegovina",
  "British Indian Ocean Territory",
  "Bulgaria",
  "Canary Islands",
  "Christmas Island (Indian Ocean)",
  "Christmas Island (Pacific Ocean)",
  "Cocos Islands",
  "Cook Island",
  "Coral Sea Island",
  "Corsica",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Estonia",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French South Antarctic Territory",
  "Georgia",
  "Germany",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Hungary",
  "Iceland",
  "Italy",
  "Kazakhstan",
  "Keeling",
  "Kiribati",
  "Kosovo",
  "Kyrgyzstan",
  "Latvia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madeira",
  "Malta",
  "Moldova",
  "Monaco",
  "Montenegro",
  "Nauru Island",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "New Zealand Antarctic Territory",
  "Niue Island",
  "Norfolk Island",
  "North America",
  "North Macedonia",
  "Norway (including Spitzbergen)",
  "Norwegian Antarctic Territory",
  "Papua New Guinea",
  "People's Democratic Republic of Laos",
  "Pitcairn Island",
  "Poland",
  "Portugal",
  "Republic of Ireland",
  "Republic of Singapore",
  "Romania",
  "Russia",
  "San Marino",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "South America",
  "South East Asia",
  "Spain",
  "Sweden",
  "Switzerland",
  "Tahiti",
  "Tajikistan",
  "the Far East",
  "the Middle East",
  "Tokelau Islands",
  "Tonga",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "US Samoa",
  "Ukraine",
  "United Kingdom",
  "United States of America",
  "Uzbekistan",
  "Vatican City State",
  "Western Samoa",
];
