import { DeliveryFeeData } from "./interfaces";

export const deliveryFeeData: DeliveryFeeData[] = [
  {
    countries: ["United Kingdom"],
    fee: 0,
    duration: 0,
  },
  {
    countries: [
      "Republic of Ireland",
      "Germany",
      "Denmark",
      "France",
      "Corsica",
      "Monaco",
    ],
    fee: 6,
    duration: 10,
  },
  {
    countries: [
      "Austria",
      "Azores",
      "Balaeric Islands",
      "Belgium",
      "Bulgaria",
      "Canary Islands",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Estonia",
      "Finland",
      "Greece",
      "Hungary",
      "Italy",
      "Latvia",
      "Lithuania",
      "Luxembourg",
      "Madeira",
      "Malta",
      "Netherlands",
      "Poland",
      "Portugal",
      "Romania",
      "Slovakia",
      "Slovenia",
      "Spain",
      "Sweden",
    ],
    fee: 6.2,
    duration: 10,
  },
  {
    countries: [
      "Albania",
      "Andorra",
      "Armenia",
      "Azerbaijan",
      "Bosnia & Herzegovina",
      "Faroe Islands",
      "Georgia",
      "Gibraltar",
      "Greenland",
      "Iceland",
      "Kazakhstan",
      "Kosovo",
      "Kyrgyzstan",
      "Liechtenstein",
      "Moldova",
      "Montenegro",
      "North Macedonia",
      "Norway (including Spitzbergen)",
      "San Marino",
      "Serbia",
      "Switzerland",
      "Tajikistan",
      "Turkey",
      "Turkmenistan",
      "Ukraine",
      "Uzbekistan",
      "Vatican City State",
    ],
    fee: 7,
    duration: 10,
  },
  {
    countries: ["United States of America"],
    fee: 7.5,
    duration: 14,
  },
  {
    countries: [
      "North America",
      "South America",
      "Africa",
      "the Middle East",
      "the Far East",
      "South East Asia",
    ],
    fee: 7.3,
    duration: 14,
  },
  {
    countries: [
      "Australia",
      "Belau",
      "British Indian Ocean Territory",
      "Christmas Island (Indian Ocean)",
      "Christmas Island (Pacific Ocean)",
      "Cocos Islands",
      "Cook Island",
      "Coral Sea Island",
      "Fiji",
      "French Polynesia",
      "French South Antarctic Territory",
      "Keeling",
      "Kiribati",
      "Macao",
      "Nauru Island",
      "New Caledonia",
      "New Zealand",
      "New Zealand Antarctic Territory",
      "Niue Island",
      "Norfolk Island",
      "Norwegian Antarctic Territory",
      "Papua New Guinea",
      "People's Democratic Republic of Laos",
      "Pitcairn Island",
      "Republic of Singapore",
      "Solomon Islands",
      "Tahiti",
      "Tokelau Islands",
      "Tonga",
      "Tuvalu",
      "US Samoa",
      "Western Samoa",
    ],
    fee: 8.5,
    duration: 14,
  },
];
